name       : rpcsvc-proto
version    : 1.4.2
release    : 1
source     :
    - https://github.com/thkukuk/rpcsvc-proto/releases/download/v1.4.2/rpcsvc-proto-1.4.2.tar.xz : 678851b9f7ddf4410d2859c12016b65a6dd1a0728d478f18aeb54d165352f17c
license    : BSD-3-Clause
component  : network.base
summary    : rpcsvc protocol definitions from glibc
description: |
    This package contains rpcsvc proto.x files from glibc, which are missing in libtirpc. Additional it contains rpcgen, which is needed to create header files and sources from protocol files. This package is only needed, if glibc is installed without the deprecated sunrpc functionality and libtirpc should replace it.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
